import type { ReactNode } from "react";
import type { BlueprintRecord } from "../core";
import {
  ApiEndpointCatalog,
  AssetProductionBoard,
  CandidatePipeline,
  CommunityFeed,
  CourseCatalogGrid,
  CustomerHealthBoard,
  DeploymentEnvironmentMatrix,
  DeviceTopologyList,
  EmployeeDirectoryGrid,
  InventorySkuMatrix,
  InvoiceCollection,
  LearnerRoster,
  LegalCaseDocket,
  ModelRegistryCollection,
  ModerationQueue,
  PromptLibraryGrid,
  PropertyListingGrid,
  ReservationCalendar,
  RouteStopTimeline,
  SensorReadingTable,
  ShipmentTrackingBoard,
  SupportTicketInbox,
  TenantDirectory,
  ThreatEventStream,
  TransactionLedger,
  TripItineraryCollection,
  VendorMarketplaceGrid,
  VenueSeatMap,
  VulnerabilityMatrix,
  WarehouseBinExplorer,
} from "../collections";
import {
  ApiProductDetail,
  CandidateDetail,
  CommunityMemberDetail,
  CourseDetail,
  CustomerSuccessDetail,
  DeploymentDetail,
  DeviceDetail,
  EmployeeProfileDetail,
  EventDetail,
  InventoryItemDetail,
  InvoiceDetail,
  KnowledgeArticleDetail,
  LearnerDetail,
  LegalMatterDetail,
  MediaAssetDetail,
  ModelDetail,
  PromptDetail,
  PropertyDetail,
  ReservationDetail,
  ShipmentDetail,
  SupportTicketDetail,
  ThreatIncidentDetail,
  TransactionDetail,
  TripDetail,
  VendorDetail,
  VulnerabilityDetail,
} from "../details";
import {
  AiModelOpsDashboard,
  ApiReliabilityDashboard,
  BillingRevenueDashboard,
  BookingOccupancyDashboard,
  CohortPerformanceDashboard,
  CommunityEngagementDashboard,
  CustomerSuccessDashboard,
  DeliveryPerformanceDashboard,
  DeveloperUsageDashboard,
  EnergyUsageDashboard,
  EventAttendanceDashboard,
  FinanceCashflowDashboard,
  HrWorkforceDashboard,
  InventoryTurnoverDashboard,
  IoTDeviceFleetDashboard,
  KnowledgeHealthDashboard,
  LearningProgressDashboard,
  LegalMatterDashboard,
  LogisticsFleetDashboard,
  MarketplaceLiquidityDashboard,
  MediaPipelineDashboard,
  PromptAnalyticsDashboard,
  PropertyOccupancyDashboard,
  RealEstatePortfolioDashboard,
  RecruitingPipelineDashboard,
  SecurityThreatDashboard,
  SocOverviewDashboard,
  SupportSlaDashboard,
  TravelOperationsDashboard,
  WarehouseCapacityDashboard,
} from "../dashboards";

// Expansion Pack(확장 팩) collection/detail/dashboard 파츠 배선. megaFactory의 균일한 시그니처
// (Collection=records/onSelect, Detail=record, Dashboard=metrics/records)를 기존 어댑터 렌더 컨텍스트
// (rows/record)로 이어붙인다. 개별 매퍼 없이 records=rows 한 줄로 끝난다. registry.tsx가 이 맵을
// 기본 파츠 맵과 합쳐 partKind/render/partsForKind/labels에 노출한다. 백엔드 BlueprintPartRegistry.ALL
// 의 componentId와 1:1로 일치한다.

type CollectionCtx = { rows: BlueprintRecord[]; onRowClick?: (row: BlueprintRecord) => void };
type DetailCtx = { record: BlueprintRecord };
type DashboardCtx = { rows: BlueprintRecord[] };
type MegaEntry =
  | { kind: "collection"; render: (ctx: CollectionCtx) => ReactNode }
  | { kind: "detail"; render: (ctx: DetailCtx) => ReactNode }
  | { kind: "dashboard"; render: (ctx: DashboardCtx) => ReactNode };

export const MEGA_BLUEPRINT_PARTS = {
  "security-threat-dashboard": { kind: "dashboard", render: ({ rows }) => <SecurityThreatDashboard metrics={[]} records={rows} /> },
  "soc-overview-dashboard": { kind: "dashboard", render: ({ rows }) => <SocOverviewDashboard metrics={[]} records={rows} /> },
  "support-sla-dashboard": { kind: "dashboard", render: ({ rows }) => <SupportSlaDashboard metrics={[]} records={rows} /> },
  "customer-success-dashboard": { kind: "dashboard", render: ({ rows }) => <CustomerSuccessDashboard metrics={[]} records={rows} /> },
  "finance-cashflow-dashboard": { kind: "dashboard", render: ({ rows }) => <FinanceCashflowDashboard metrics={[]} records={rows} /> },
  "billing-revenue-dashboard": { kind: "dashboard", render: ({ rows }) => <BillingRevenueDashboard metrics={[]} records={rows} /> },
  "inventory-turnover-dashboard": { kind: "dashboard", render: ({ rows }) => <InventoryTurnoverDashboard metrics={[]} records={rows} /> },
  "warehouse-capacity-dashboard": { kind: "dashboard", render: ({ rows }) => <WarehouseCapacityDashboard metrics={[]} records={rows} /> },
  "logistics-fleet-dashboard": { kind: "dashboard", render: ({ rows }) => <LogisticsFleetDashboard metrics={[]} records={rows} /> },
  "delivery-performance-dashboard": { kind: "dashboard", render: ({ rows }) => <DeliveryPerformanceDashboard metrics={[]} records={rows} /> },
  "booking-occupancy-dashboard": { kind: "dashboard", render: ({ rows }) => <BookingOccupancyDashboard metrics={[]} records={rows} /> },
  "event-attendance-dashboard": { kind: "dashboard", render: ({ rows }) => <EventAttendanceDashboard metrics={[]} records={rows} /> },
  "learning-progress-dashboard": { kind: "dashboard", render: ({ rows }) => <LearningProgressDashboard metrics={[]} records={rows} /> },
  "cohort-performance-dashboard": { kind: "dashboard", render: ({ rows }) => <CohortPerformanceDashboard metrics={[]} records={rows} /> },
  "hr-workforce-dashboard": { kind: "dashboard", render: ({ rows }) => <HrWorkforceDashboard metrics={[]} records={rows} /> },
  "recruiting-pipeline-dashboard": { kind: "dashboard", render: ({ rows }) => <RecruitingPipelineDashboard metrics={[]} records={rows} /> },
  "developer-usage-dashboard": { kind: "dashboard", render: ({ rows }) => <DeveloperUsageDashboard metrics={[]} records={rows} /> },
  "api-reliability-dashboard": { kind: "dashboard", render: ({ rows }) => <ApiReliabilityDashboard metrics={[]} records={rows} /> },
  "ai-model-ops-dashboard": { kind: "dashboard", render: ({ rows }) => <AiModelOpsDashboard metrics={[]} records={rows} /> },
  "prompt-analytics-dashboard": { kind: "dashboard", render: ({ rows }) => <PromptAnalyticsDashboard metrics={[]} records={rows} /> },
  "iot-device-fleet-dashboard": { kind: "dashboard", render: ({ rows }) => <IoTDeviceFleetDashboard metrics={[]} records={rows} /> },
  "energy-usage-dashboard": { kind: "dashboard", render: ({ rows }) => <EnergyUsageDashboard metrics={[]} records={rows} /> },
  "real-estate-portfolio-dashboard": { kind: "dashboard", render: ({ rows }) => <RealEstatePortfolioDashboard metrics={[]} records={rows} /> },
  "property-occupancy-dashboard": { kind: "dashboard", render: ({ rows }) => <PropertyOccupancyDashboard metrics={[]} records={rows} /> },
  "community-engagement-dashboard": { kind: "dashboard", render: ({ rows }) => <CommunityEngagementDashboard metrics={[]} records={rows} /> },
  "marketplace-liquidity-dashboard": { kind: "dashboard", render: ({ rows }) => <MarketplaceLiquidityDashboard metrics={[]} records={rows} /> },
  "travel-operations-dashboard": { kind: "dashboard", render: ({ rows }) => <TravelOperationsDashboard metrics={[]} records={rows} /> },
  "legal-matter-dashboard": { kind: "dashboard", render: ({ rows }) => <LegalMatterDashboard metrics={[]} records={rows} /> },
  "media-pipeline-dashboard": { kind: "dashboard", render: ({ rows }) => <MediaPipelineDashboard metrics={[]} records={rows} /> },
  "knowledge-health-dashboard": { kind: "dashboard", render: ({ rows }) => <KnowledgeHealthDashboard metrics={[]} records={rows} /> },
  "threat-event-stream": { kind: "collection", render: ({ rows, onRowClick }) => <ThreatEventStream records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "vulnerability-matrix": { kind: "collection", render: ({ rows, onRowClick }) => <VulnerabilityMatrix records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "support-ticket-inbox": { kind: "collection", render: ({ rows, onRowClick }) => <SupportTicketInbox records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "customer-health-board": { kind: "collection", render: ({ rows, onRowClick }) => <CustomerHealthBoard records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "transaction-ledger": { kind: "collection", render: ({ rows, onRowClick }) => <TransactionLedger records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "invoice-collection": { kind: "collection", render: ({ rows, onRowClick }) => <InvoiceCollection records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "inventory-sku-matrix": { kind: "collection", render: ({ rows, onRowClick }) => <InventorySkuMatrix records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "warehouse-bin-explorer": { kind: "collection", render: ({ rows, onRowClick }) => <WarehouseBinExplorer records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "shipment-tracking-board": { kind: "collection", render: ({ rows, onRowClick }) => <ShipmentTrackingBoard records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "route-stop-timeline": { kind: "collection", render: ({ rows, onRowClick }) => <RouteStopTimeline records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "reservation-calendar": { kind: "collection", render: ({ rows, onRowClick }) => <ReservationCalendar records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "venue-seat-map": { kind: "collection", render: ({ rows, onRowClick }) => <VenueSeatMap records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "course-catalog-grid": { kind: "collection", render: ({ rows, onRowClick }) => <CourseCatalogGrid records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "learner-roster": { kind: "collection", render: ({ rows, onRowClick }) => <LearnerRoster records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "employee-directory-grid": { kind: "collection", render: ({ rows, onRowClick }) => <EmployeeDirectoryGrid records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "candidate-pipeline": { kind: "collection", render: ({ rows, onRowClick }) => <CandidatePipeline records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "api-endpoint-catalog": { kind: "collection", render: ({ rows, onRowClick }) => <ApiEndpointCatalog records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "deployment-environment-matrix": { kind: "collection", render: ({ rows, onRowClick }) => <DeploymentEnvironmentMatrix records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "model-registry-collection": { kind: "collection", render: ({ rows, onRowClick }) => <ModelRegistryCollection records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "prompt-library-grid": { kind: "collection", render: ({ rows, onRowClick }) => <PromptLibraryGrid records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "device-topology-list": { kind: "collection", render: ({ rows, onRowClick }) => <DeviceTopologyList records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "sensor-reading-table": { kind: "collection", render: ({ rows, onRowClick }) => <SensorReadingTable records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "property-listing-grid": { kind: "collection", render: ({ rows, onRowClick }) => <PropertyListingGrid records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "tenant-directory": { kind: "collection", render: ({ rows, onRowClick }) => <TenantDirectory records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "community-feed": { kind: "collection", render: ({ rows, onRowClick }) => <CommunityFeed records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "moderation-queue": { kind: "collection", render: ({ rows, onRowClick }) => <ModerationQueue records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "vendor-marketplace-grid": { kind: "collection", render: ({ rows, onRowClick }) => <VendorMarketplaceGrid records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "trip-itinerary-collection": { kind: "collection", render: ({ rows, onRowClick }) => <TripItineraryCollection records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "legal-case-docket": { kind: "collection", render: ({ rows, onRowClick }) => <LegalCaseDocket records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "asset-production-board": { kind: "collection", render: ({ rows, onRowClick }) => <AssetProductionBoard records={rows} onSelect={(record) => onRowClick?.(record)} /> },
  "threat-incident-detail": { kind: "detail", render: ({ record }) => <ThreatIncidentDetail record={record} /> },
  "vulnerability-detail": { kind: "detail", render: ({ record }) => <VulnerabilityDetail record={record} /> },
  "support-ticket-detail": { kind: "detail", render: ({ record }) => <SupportTicketDetail record={record} /> },
  "customer-success-detail": { kind: "detail", render: ({ record }) => <CustomerSuccessDetail record={record} /> },
  "transaction-detail": { kind: "detail", render: ({ record }) => <TransactionDetail record={record} /> },
  "invoice-detail": { kind: "detail", render: ({ record }) => <InvoiceDetail record={record} /> },
  "inventory-item-detail": { kind: "detail", render: ({ record }) => <InventoryItemDetail record={record} /> },
  "shipment-detail": { kind: "detail", render: ({ record }) => <ShipmentDetail record={record} /> },
  "reservation-detail": { kind: "detail", render: ({ record }) => <ReservationDetail record={record} /> },
  "event-detail": { kind: "detail", render: ({ record }) => <EventDetail record={record} /> },
  "course-detail": { kind: "detail", render: ({ record }) => <CourseDetail record={record} /> },
  "learner-detail": { kind: "detail", render: ({ record }) => <LearnerDetail record={record} /> },
  "employee-profile-detail": { kind: "detail", render: ({ record }) => <EmployeeProfileDetail record={record} /> },
  "candidate-detail": { kind: "detail", render: ({ record }) => <CandidateDetail record={record} /> },
  "api-product-detail": { kind: "detail", render: ({ record }) => <ApiProductDetail record={record} /> },
  "deployment-detail": { kind: "detail", render: ({ record }) => <DeploymentDetail record={record} /> },
  "model-detail": { kind: "detail", render: ({ record }) => <ModelDetail record={record} /> },
  "prompt-detail": { kind: "detail", render: ({ record }) => <PromptDetail record={record} /> },
  "device-detail": { kind: "detail", render: ({ record }) => <DeviceDetail record={record} /> },
  "property-detail": { kind: "detail", render: ({ record }) => <PropertyDetail record={record} /> },
  "community-member-detail": { kind: "detail", render: ({ record }) => <CommunityMemberDetail record={record} /> },
  "vendor-detail": { kind: "detail", render: ({ record }) => <VendorDetail record={record} /> },
  "trip-detail": { kind: "detail", render: ({ record }) => <TripDetail record={record} /> },
  "legal-matter-detail": { kind: "detail", render: ({ record }) => <LegalMatterDetail record={record} /> },
  "media-asset-detail": { kind: "detail", render: ({ record }) => <MediaAssetDetail record={record} /> },
  "knowledge-article-detail": { kind: "detail", render: ({ record }) => <KnowledgeArticleDetail record={record} /> },
} satisfies Record<string, MegaEntry>;

export const MEGA_BLUEPRINT_PART_LABELS: Record<string, string> = {
  "security-threat-dashboard": "Security Threat Dashboard",
  "soc-overview-dashboard": "Soc Overview Dashboard",
  "support-sla-dashboard": "Support Sla Dashboard",
  "customer-success-dashboard": "Customer Success Dashboard",
  "finance-cashflow-dashboard": "Finance Cashflow Dashboard",
  "billing-revenue-dashboard": "Billing Revenue Dashboard",
  "inventory-turnover-dashboard": "Inventory Turnover Dashboard",
  "warehouse-capacity-dashboard": "Warehouse Capacity Dashboard",
  "logistics-fleet-dashboard": "Logistics Fleet Dashboard",
  "delivery-performance-dashboard": "Delivery Performance Dashboard",
  "booking-occupancy-dashboard": "Booking Occupancy Dashboard",
  "event-attendance-dashboard": "Event Attendance Dashboard",
  "learning-progress-dashboard": "Learning Progress Dashboard",
  "cohort-performance-dashboard": "Cohort Performance Dashboard",
  "hr-workforce-dashboard": "Hr Workforce Dashboard",
  "recruiting-pipeline-dashboard": "Recruiting Pipeline Dashboard",
  "developer-usage-dashboard": "Developer Usage Dashboard",
  "api-reliability-dashboard": "Api Reliability Dashboard",
  "ai-model-ops-dashboard": "Ai Model Ops Dashboard",
  "prompt-analytics-dashboard": "Prompt Analytics Dashboard",
  "iot-device-fleet-dashboard": "Iot Device Fleet Dashboard",
  "energy-usage-dashboard": "Energy Usage Dashboard",
  "real-estate-portfolio-dashboard": "Real Estate Portfolio Dashboard",
  "property-occupancy-dashboard": "Property Occupancy Dashboard",
  "community-engagement-dashboard": "Community Engagement Dashboard",
  "marketplace-liquidity-dashboard": "Marketplace Liquidity Dashboard",
  "travel-operations-dashboard": "Travel Operations Dashboard",
  "legal-matter-dashboard": "Legal Matter Dashboard",
  "media-pipeline-dashboard": "Media Pipeline Dashboard",
  "knowledge-health-dashboard": "Knowledge Health Dashboard",
  "threat-event-stream": "Threat Event Stream",
  "vulnerability-matrix": "Vulnerability Matrix",
  "support-ticket-inbox": "Support Ticket Inbox",
  "customer-health-board": "Customer Health Board",
  "transaction-ledger": "Transaction Ledger",
  "invoice-collection": "Invoice Collection",
  "inventory-sku-matrix": "Inventory Sku Matrix",
  "warehouse-bin-explorer": "Warehouse Bin Explorer",
  "shipment-tracking-board": "Shipment Tracking Board",
  "route-stop-timeline": "Route Stop Timeline",
  "reservation-calendar": "Reservation Calendar",
  "venue-seat-map": "Venue Seat Map",
  "course-catalog-grid": "Course Catalog Grid",
  "learner-roster": "Learner Roster",
  "employee-directory-grid": "Employee Directory Grid",
  "candidate-pipeline": "Candidate Pipeline",
  "api-endpoint-catalog": "Api Endpoint Catalog",
  "deployment-environment-matrix": "Deployment Environment Matrix",
  "model-registry-collection": "Model Registry Collection",
  "prompt-library-grid": "Prompt Library Grid",
  "device-topology-list": "Device Topology List",
  "sensor-reading-table": "Sensor Reading Table",
  "property-listing-grid": "Property Listing Grid",
  "tenant-directory": "Tenant Directory",
  "community-feed": "Community Feed",
  "moderation-queue": "Moderation Queue",
  "vendor-marketplace-grid": "Vendor Marketplace Grid",
  "trip-itinerary-collection": "Trip Itinerary Collection",
  "legal-case-docket": "Legal Case Docket",
  "asset-production-board": "Asset Production Board",
  "threat-incident-detail": "Threat Incident Detail",
  "vulnerability-detail": "Vulnerability Detail",
  "support-ticket-detail": "Support Ticket Detail",
  "customer-success-detail": "Customer Success Detail",
  "transaction-detail": "Transaction Detail",
  "invoice-detail": "Invoice Detail",
  "inventory-item-detail": "Inventory Item Detail",
  "shipment-detail": "Shipment Detail",
  "reservation-detail": "Reservation Detail",
  "event-detail": "Event Detail",
  "course-detail": "Course Detail",
  "learner-detail": "Learner Detail",
  "employee-profile-detail": "Employee Profile Detail",
  "candidate-detail": "Candidate Detail",
  "api-product-detail": "Api Product Detail",
  "deployment-detail": "Deployment Detail",
  "model-detail": "Model Detail",
  "prompt-detail": "Prompt Detail",
  "device-detail": "Device Detail",
  "property-detail": "Property Detail",
  "community-member-detail": "Community Member Detail",
  "vendor-detail": "Vendor Detail",
  "trip-detail": "Trip Detail",
  "legal-matter-detail": "Legal Matter Detail",
  "media-asset-detail": "Media Asset Detail",
  "knowledge-article-detail": "Knowledge Article Detail",
};
