import type { CSSProperties } from "react";
import type { PreviewCompiledScenario } from "@/lib/types";
import type { PreviewCapability } from "../types";
import type { ProductArchetype } from "./productExperience";

export type ProductThemeStyle = CSSProperties & Record<`--${string}`, string | number>;

export interface ProductExperienceTheme {
  id: string;
  blueprintThemeId: string;
  label: string;
  colorScheme: "light" | "dark";
  style: ProductThemeStyle;
}

type Palette = {
  id: string;
  blueprintThemeId: string;
  label: string;
  colorScheme?: "light" | "dark";
  background: string;
  surface: string;
  surfaceSoft: string;
  ink: string;
  muted: string;
  subtle: string;
  line: string;
  lineStrong: string;
  accent: string;
  accentHover: string;
  onAccent: string;
  tint: string;
  tintStrong: string;
  secondary: string;
  secondaryTint: string;
  hero: string;
  heroInk: string;
  heroMuted: string;
  visualA: string;
  visualB: string;
  visualC: string;
  visualD: string;
  danger?: string;
  dangerInk?: string;
  dangerBackground?: string;
  success?: string;
  successBackground?: string;
};

const PALETTES: Record<string, Palette> = {
  calendar: {
    id: "calendar-sage",
    blueprintThemeId: "soft-pastel-theme",
    label: "Calm sage",
    background: "#f3f6f1",
    surface: "#ffffff",
    surfaceSoft: "#f7f9f6",
    ink: "#182019",
    muted: "#687269",
    subtle: "#919a92",
    line: "#dfe6df",
    lineStrong: "#cbd6cc",
    accent: "#496f54",
    accentHover: "#375b42",
    onAccent: "#ffffff",
    tint: "#e5efe6",
    tintStrong: "#cde1d0",
    secondary: "#9a7049",
    secondaryTint: "#f2e8dc",
    hero: "#1f3425",
    heroInk: "#f5fbf6",
    heroMuted: "#b6cfba",
    visualA: "#d6e7d8",
    visualB: "#f1e2cf",
    visualC: "#dbe7ef",
    visualD: "#e7dff1",
  },
  commerce: {
    id: "warm-commerce",
    blueprintThemeId: "warm-commerce-theme",
    label: "Warm commerce",
    background: "#faf5ef",
    surface: "#fffdf9",
    surfaceSoft: "#f8eee4",
    ink: "#2b201a",
    muted: "#796b62",
    subtle: "#a09389",
    line: "#eadfd5",
    lineStrong: "#d8c6b7",
    accent: "#b5522b",
    accentHover: "#94401f",
    onAccent: "#fffaf5",
    tint: "#f7e3d5",
    tintStrong: "#efc5ab",
    secondary: "#7e5d91",
    secondaryTint: "#eee5f2",
    hero: "#43291f",
    heroInk: "#fff8ef",
    heroMuted: "#e8c8b3",
    visualA: "#efcfb8",
    visualB: "#f6e3bd",
    visualC: "#d8dfc9",
    visualD: "#e2cfdf",
  },
  community: {
    id: "social-coral",
    blueprintThemeId: "sunset-operations-theme",
    label: "Social coral",
    background: "#fff7f6",
    surface: "#ffffff",
    surfaceSoft: "#fdf0ee",
    ink: "#2b2023",
    muted: "#78696d",
    subtle: "#a49196",
    line: "#eddde0",
    lineStrong: "#ddc7cc",
    accent: "#b8445b",
    accentHover: "#9d3349",
    onAccent: "#ffffff",
    tint: "#fbe2e7",
    tintStrong: "#f3bec9",
    secondary: "#6e61a8",
    secondaryTint: "#e9e5f5",
    hero: "#3a2029",
    heroInk: "#fff7f9",
    heroMuted: "#e7bdc8",
    visualA: "#f3cbd2",
    visualB: "#f3dfc9",
    visualC: "#d9d5ef",
    visualD: "#cee4dd",
  },
  editorial: {
    id: "editorial-paper",
    blueprintThemeId: "editorial-paper-theme",
    label: "Editorial paper",
    background: "#f0ebe1",
    surface: "#fbf8f1",
    surfaceSoft: "#f5f0e7",
    ink: "#24201b",
    muted: "#706960",
    subtle: "#968e83",
    line: "#ddd5c8",
    lineStrong: "#c9bcaa",
    accent: "#8a5a32",
    accentHover: "#704521",
    onAccent: "#fffaf2",
    tint: "#eee0ce",
    tintStrong: "#dcc1a2",
    secondary: "#5d6e65",
    secondaryTint: "#dfe7e1",
    hero: "#302820",
    heroInk: "#fffaf0",
    heroMuted: "#d7c7b2",
    visualA: "#e1c8a8",
    visualB: "#d8d0bc",
    visualC: "#c8d3cc",
    visualD: "#d8cbd0",
  },
  booking: {
    id: "coastal-booking",
    blueprintThemeId: "ocean-data-theme",
    label: "Coastal booking",
    background: "#f2f7f8",
    surface: "#ffffff",
    surfaceSoft: "#edf5f6",
    ink: "#15272b",
    muted: "#60767b",
    subtle: "#8da0a4",
    line: "#d8e5e7",
    lineStrong: "#bfd4d7",
    accent: "#16778a",
    accentHover: "#0e6171",
    onAccent: "#ffffff",
    tint: "#dceff2",
    tintStrong: "#b7dce2",
    secondary: "#b56d42",
    secondaryTint: "#f3e4d8",
    hero: "#123943",
    heroInk: "#f0fcff",
    heroMuted: "#a9d4dc",
    visualA: "#c9e3e7",
    visualB: "#e7dcc6",
    visualC: "#cfdceb",
    visualD: "#d6e6d8",
  },
  messaging: {
    id: "relay-blue",
    blueprintThemeId: "enterprise-blue-theme",
    label: "Relay blue",
    background: "#f3f6fb",
    surface: "#ffffff",
    surfaceSoft: "#edf2f9",
    ink: "#182231",
    muted: "#687587",
    subtle: "#94a0af",
    line: "#dce4ef",
    lineStrong: "#c5d2e2",
    accent: "#356eb8",
    accentHover: "#285a9b",
    onAccent: "#ffffff",
    tint: "#e1ebf8",
    tintStrong: "#c0d5ef",
    secondary: "#6c5aa7",
    secondaryTint: "#e9e5f4",
    hero: "#1c3150",
    heroInk: "#f6f9ff",
    heroMuted: "#b9cce8",
    visualA: "#c9d9ee",
    visualB: "#d9e5f3",
    visualC: "#d9d3ee",
    visualD: "#d3e5df",
  },
  files: {
    id: "cloud-cyan",
    blueprintThemeId: "glass-aurora-theme",
    label: "Cloud cyan",
    background: "#f1f8f8",
    surface: "#ffffff",
    surfaceSoft: "#eaf5f4",
    ink: "#152827",
    muted: "#617675",
    subtle: "#90a3a2",
    line: "#d6e7e5",
    lineStrong: "#bdd8d5",
    accent: "#12817c",
    accentHover: "#0a6965",
    onAccent: "#ffffff",
    tint: "#d8efed",
    tintStrong: "#afe0dc",
    secondary: "#7564a6",
    secondaryTint: "#e8e3f2",
    hero: "#153b3a",
    heroInk: "#effdfc",
    heroMuted: "#add7d4",
    visualA: "#bfe3df",
    visualB: "#dbe9d3",
    visualC: "#cbdcef",
    visualD: "#ddd4ec",
  },
  learning: {
    id: "lavender-learning",
    blueprintThemeId: "lavender-creator-theme",
    label: "Lavender learning",
    background: "#f7f4fb",
    surface: "#ffffff",
    surfaceSoft: "#f1edf8",
    ink: "#282236",
    muted: "#756d83",
    subtle: "#9c94a8",
    line: "#e5deee",
    lineStrong: "#d1c5df",
    accent: "#7658a8",
    accentHover: "#62458f",
    onAccent: "#ffffff",
    tint: "#ebe3f5",
    tintStrong: "#d6c5e9",
    secondary: "#b66678",
    secondaryTint: "#f4e2e6",
    hero: "#35294a",
    heroInk: "#fbf8ff",
    heroMuted: "#d2c3e6",
    visualA: "#d9caeb",
    visualB: "#efdadf",
    visualC: "#d2e4dc",
    visualD: "#e9dfc7",
  },
  workspace: {
    id: "forest-workspace",
    blueprintThemeId: "forest-saas-theme",
    label: "Forest workspace",
    background: "#f3f6f2",
    surface: "#ffffff",
    surfaceSoft: "#eef3ed",
    ink: "#192219",
    muted: "#69736a",
    subtle: "#929b93",
    line: "#dce4dc",
    lineStrong: "#c6d2c7",
    accent: "#3e6e49",
    accentHover: "#2e5a39",
    onAccent: "#ffffff",
    tint: "#e0ece1",
    tintStrong: "#bfdbbf",
    secondary: "#8f6b45",
    secondaryTint: "#efe4d6",
    hero: "#203925",
    heroInk: "#f4fbf4",
    heroMuted: "#b8d1ba",
    visualA: "#cce1ce",
    visualB: "#eadcc8",
    visualC: "#cedee8",
    visualD: "#ddd3e6",
  },
  admin: {
    id: "monochrome-admin",
    blueprintThemeId: "monochrome-pro-theme",
    label: "Monochrome pro",
    background: "#f4f5f6",
    surface: "#ffffff",
    surfaceSoft: "#eff1f3",
    ink: "#181b1f",
    muted: "#687079",
    subtle: "#939aa2",
    line: "#dfe3e7",
    lineStrong: "#c8ced5",
    accent: "#303840",
    accentHover: "#1e252c",
    onAccent: "#ffffff",
    tint: "#e5e9ed",
    tintStrong: "#cfd6dc",
    secondary: "#536b82",
    secondaryTint: "#e0e8ef",
    hero: "#22272d",
    heroInk: "#f8fafb",
    heroMuted: "#c2c9d0",
    visualA: "#d4dbe1",
    visualB: "#e4ded5",
    visualC: "#ccd9df",
    visualD: "#dcd6df",
  },
  security: {
    id: "crimson-security",
    blueprintThemeId: "crimson-security-theme",
    label: "Crimson security",
    colorScheme: "dark",
    background: "#10090b",
    surface: "#191114",
    surfaceSoft: "#211519",
    ink: "#fff4f5",
    muted: "#c8aeb3",
    subtle: "#8e7379",
    line: "#3a2429",
    lineStrong: "#553139",
    accent: "#f06072",
    accentHover: "#ff7585",
    onAccent: "#26070d",
    tint: "#32171d",
    tintStrong: "#51212b",
    secondary: "#d7a759",
    secondaryTint: "#332817",
    hero: "#2a0d13",
    heroInk: "#fff5f6",
    heroMuted: "#e5aab4",
    visualA: "#4a1c25",
    visualB: "#39242b",
    visualC: "#29233f",
    visualD: "#3e2820",
    danger: "#ff6678",
    dangerInk: "#26070d",
    dangerBackground: "#35131a",
    success: "#5bd29a",
    successBackground: "#102a20",
  },
  finance: {
    id: "sandstone-finance",
    blueprintThemeId: "sandstone-finance-theme",
    label: "Sandstone finance",
    background: "#f5f0e7",
    surface: "#fffdf8",
    surfaceSoft: "#eee5d6",
    ink: "#272119",
    muted: "#756b5e",
    subtle: "#9c9182",
    line: "#e1d6c5",
    lineStrong: "#cbbba3",
    accent: "#96632d",
    accentHover: "#7c5123",
    onAccent: "#fffaf1",
    tint: "#eadcc7",
    tintStrong: "#d7bd98",
    secondary: "#536d66",
    secondaryTint: "#dfe8e3",
    hero: "#392d20",
    heroInk: "#fff9ef",
    heroMuted: "#ddc7a7",
    visualA: "#ddc49f",
    visualB: "#e8dbc5",
    visualC: "#cbd9d2",
    visualD: "#d7ceda",
  },
  technology: {
    id: "aurora-technology",
    blueprintThemeId: "neon-cyber-theme",
    label: "Aurora technology",
    colorScheme: "dark",
    background: "#0b0b17",
    surface: "#131421",
    surfaceSoft: "#191a2a",
    ink: "#f5f4ff",
    muted: "#b3b0c9",
    subtle: "#7d7995",
    line: "#2c2d43",
    lineStrong: "#41435f",
    accent: "#9f7aea",
    accentHover: "#b596f1",
    onAccent: "#160d2a",
    tint: "#251c3b",
    tintStrong: "#3a285c",
    secondary: "#39c5d5",
    secondaryTint: "#15333b",
    hero: "#171128",
    heroInk: "#fbf8ff",
    heroMuted: "#c5b4e6",
    visualA: "#382758",
    visualB: "#153944",
    visualC: "#263252",
    visualD: "#48243f",
    success: "#5bd6a0",
    successBackground: "#102d22",
  },
};

function searchableText(
  scenarios: PreviewCompiledScenario[],
  capabilities: PreviewCapability[]
): string {
  return [
    ...scenarios.flatMap((scenario) => [
      scenario.name,
      scenario.goal,
      scenario.actor,
      ...scenario.stages.flatMap((stage) => [stage.intent, stage.operationId ?? ""]),
    ]),
    ...capabilities.flatMap((capability) => [
      capability.resourceName,
      capability.operationId ?? "",
      capability.action ?? "",
      capability.path,
    ]),
  ].join(" ").toLowerCase();
}

function paletteFor(
  archetype: ProductArchetype,
  scenarios: PreviewCompiledScenario[],
  capabilities: PreviewCapability[]
): Palette {
  const text = searchableText(scenarios, capabilities);
  if (/(security|threat|incident|vulnerab|firewall|보안|위협|침해|취약)/.test(text)) return PALETTES.security;
  if (/(finance|payment|invoice|billing|transaction|refund|결제|청구|송금|환불|금융)/.test(text)) return PALETTES.finance;
  if (/(artificial intelligence|machine learning|model|prompt|developer|api platform|ai |인공지능|모델|프롬프트|개발자)/.test(text)) return PALETTES.technology;
  return {
    CALENDAR: PALETTES.calendar,
    COMMERCE: PALETTES.commerce,
    COMMUNITY: PALETTES.community,
    CONTENT: PALETTES.editorial,
    BOOKING: PALETTES.booking,
    MESSAGING: PALETTES.messaging,
    FILES: PALETTES.files,
    LEARNING: PALETTES.learning,
    WORKSPACE: PALETTES.workspace,
    ADMIN: PALETTES.admin,
  }[archetype];
}

function toStyle(palette: Palette): ProductThemeStyle {
  const danger = palette.danger ?? "#b53d45";
  const dangerBackground = palette.dangerBackground ?? "#fff0ef";
  const success = palette.success ?? "#388b5b";
  const successBackground = palette.successBackground ?? "#e7f4eb";
  return {
    "--px-bg": palette.background,
    "--px-surface": palette.surface,
    "--px-surface-soft": palette.surfaceSoft,
    "--px-ink": palette.ink,
    "--px-muted": palette.muted,
    "--px-subtle": palette.subtle,
    "--px-line": palette.line,
    "--px-line-strong": palette.lineStrong,
    "--px-accent": palette.accent,
    "--px-accent-hover": palette.accentHover,
    "--px-on-accent": palette.onAccent,
    "--px-tint": palette.tint,
    "--px-tint-strong": palette.tintStrong,
    "--px-secondary": palette.secondary,
    "--px-secondary-tint": palette.secondaryTint,
    "--px-hero": palette.hero,
    "--px-hero-ink": palette.heroInk,
    "--px-hero-muted": palette.heroMuted,
    "--px-visual-a": palette.visualA,
    "--px-visual-b": palette.visualB,
    "--px-visual-c": palette.visualC,
    "--px-visual-d": palette.visualD,
    "--px-danger": danger,
    "--px-danger-bg": dangerBackground,
    "--px-success": success,
    "--px-success-bg": successBackground,
    "--px-shadow-sm": `0 10px 35px color-mix(in srgb, ${palette.ink} 7%, transparent)`,
    "--px-shadow-md": `0 18px 45px color-mix(in srgb, ${palette.ink} 13%, transparent)`,
    "--px-shadow-lg": `0 24px 80px color-mix(in srgb, ${palette.ink} 16%, transparent)`,

    // 기존 Blueprint/공용 UI 토큰도 같은 팔레트로 덮어 모달과 삽입 파츠까지 동일한 분위기를 쓴다.
    "--background": palette.surface,
    "--foreground": palette.ink,
    "--brand": palette.accent,
    "--brand-strong": palette.accentHover,
    "--panel": palette.surfaceSoft,
    "--line": palette.line,
    "--line-strong": palette.lineStrong,
    "--muted": palette.muted,
    "--muted-soft": palette.subtle,
    "--soft": palette.tint,
    "--danger": danger,
    "--danger-soft": dangerBackground,
    "--success": success,
    "--success-soft": successBackground,
    "--accent": palette.secondary,
    "--accent-soft": palette.secondaryTint,
    "--preview-status-ok": success,
    "--preview-status-warn": palette.secondary,
    "--preview-status-idle": palette.subtle,
    "--preview-status-danger": danger,
    "--preview-blueprint-brand": palette.accent,
    "--preview-theme-accent": palette.secondary,
    "--preview-blueprint-surface-raised": palette.surface,
    "--preview-blueprint-surface-soft": palette.surfaceSoft,
    "--preview-blueprint-shadow": "var(--px-shadow-md)",
    "--button-primary-ink": palette.onAccent,
    "--button-secondary-ink": palette.ink,
    "--button-danger-ink": palette.dangerInk ?? "#ffffff",
    "--button-danger-hover": `color-mix(in srgb, ${danger} 84%, ${palette.ink})`,
    colorScheme: palette.colorScheme ?? "light",
  };
}

export function selectProductExperienceTheme(
  archetype: ProductArchetype,
  scenarios: PreviewCompiledScenario[],
  capabilities: PreviewCapability[]
): ProductExperienceTheme {
  const palette = paletteFor(archetype, scenarios, capabilities);
  return {
    id: palette.id,
    blueprintThemeId: palette.blueprintThemeId,
    label: palette.label,
    colorScheme: palette.colorScheme ?? "light",
    style: toStyle(palette),
  };
}
