import { Avatar } from "@/components/ui/avatar";
import { BlueprintActionButtons, BlueprintKeyValueGrid, BlueprintMetricGrid, BlueprintSection, BlueprintStatusPill, formatBlueprintValue } from "../core";
import type { BlueprintAction, BlueprintField, BlueprintMetric, BlueprintRecord, BlueprintTimelineEvent } from "../core";
import { TimelineCollection } from "../collections";

export function CustomerProfileDetail({ profile, metrics, fields, actions, activity, segments = [], onAction }: { profile: BlueprintRecord; metrics: BlueprintMetric[]; fields: BlueprintField[]; actions: BlueprintAction[]; activity?: BlueprintTimelineEvent[]; segments?: string[]; onAction?: (action: BlueprintAction) => void }) {
  const title = formatBlueprintValue(profile.name ?? profile.fullName ?? profile.email);
  return <div className="space-y-4"><header className="rounded-[18px] border border-line bg-panel p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><Avatar nickname={title} email={typeof profile.email === "string" ? profile.email : undefined} profileImageUrl={typeof profile.avatarUrl === "string" ? profile.avatarUrl : undefined} sizePx={64} textSizeClassName="text-lg" /><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-black">{title}</h2><BlueprintStatusPill value={profile.status ?? "active"} /></div><p className="mt-1 text-sm text-muted-soft">{formatBlueprintValue(profile.email ?? profile.phone)}</p><div className="mt-2 flex flex-wrap gap-1.5">{segments.map((segment) => <span key={segment} className="rounded-full bg-white/[0.05] px-2 py-1 text-[10px] text-muted">{segment}</span>)}</div></div></div><BlueprintActionButtons actions={actions} onAction={onAction} /></div></header><BlueprintMetricGrid metrics={metrics} columns={4} /><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]"><BlueprintSection title="Profile" description="Identity, contact, and account attributes."><BlueprintKeyValueGrid fields={fields} columns={2} /></BlueprintSection>{activity && <BlueprintSection title="Customer journey"><TimelineCollection events={activity} compact /></BlueprintSection>}</div></div>;
}
