upstream auth_upstream {
    server auth:8080;
}

upstream user_upstream {
    server user:8080;
}

upstream swagger_ui_upstream {
    server swagger-ui:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://swagger_ui_upstream;
        proxy_set_header Host $host;
    }

    location /api-docs/auth {
        proxy_pass http://auth_upstream/v3/api-docs;
        proxy_set_header Host $host;
    }

    location /api-docs/user {
        proxy_pass http://user_upstream/v3/api-docs;
        proxy_set_header Host $host;
    }

    location /auth/ {
        proxy_pass http://auth_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /users/ {
        proxy_pass http://user_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
