name: Deploy Auth to ops-01

on:
  push:
    branches: [develop]
    paths:
      - 'Backend/Auth/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code in production directory
        run: |
          cd ~/GJ-Cloud
          git fetch origin develop
          git reset --hard origin/develop

      - name: Build and deploy
        run: |
          docker compose down auth --rmi local
          docker compose up auth -d --build
